name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: "27.0.11718014"
          sdk-platform: "android-35"
          build-tools: "35.0.0"

      - name: Set NDK environment variables
        shell: pwsh
        run: |
          $ndkPath = Join-Path $env:ANDROID_HOME "ndk"
          $ndkVersion = (Get-ChildItem $ndkPath | Sort-Object Name -Descending | Select-Object -First 1).Name
          $fullNdkPath = Join-Path $ndkPath $ndkVersion
          echo "NDK_HOME=$fullNdkPath" >> $env:GITHUB_ENV
          echo "ANDROID_NDK_HOME=$fullNdkPath" >> $env:GITHUB_ENV

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: "windows-ci"

      - name: Build with Gradle
        run: .\gradlew build -Dorg.gradle.daemon=false --stacktrace
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: LeviLauncher
          path: .\app\build\outputs\apk
